Repository openedx/edx-ora2, pull requests merged in 2020-12, with the labels that each got.

#1502 [BB-2961] [BD-05] [TNL-7577] Added a templating mixin
  openassessment/locale/en/LC_MESSAGES/django.po
  openassessment/locale/en/LC_MESSAGES/djangojs.po
  openassessment/locale/eo/LC_MESSAGES/django.po
  openassessment/locale/eo/LC_MESSAGES/djangojs.po
  openassessment/xblock/defaults.py
  openassessment/xblock/openassesment_template_mixin.py
  openassessment/xblock/openassessmentblock.py
  package.json
  setup.py
Labels: blended, needs triage

#1486 [BD-5] [TNL-7337] Make peer dependent steps skippable
  openassessment/assessment/api/peer.py
  openassessment/workflow/migrations/0004_assessmentworkflowstep_skipped.py
  openassessment/workflow/models.py
  openassessment/workflow/test/test_api.py
  openassessment/xblock/peer_assessment_mixin.py
  openassessment/xblock/test/test_peer.py
  openassessment/xblock/test/test_self.py
  package.json
  setup.py
Labels: blended, needs triage

#1535 [BD-05] [BB-2992] [TNL-7578] Fix ORA grade explanation bug
  openassessment/xblock/openassessmentblock.py
  openassessment/xblock/test/data/grade_scenario_self_staff_not_required.xml
  openassessment/xblock/test/test_openassessment.py
  package.json
  setup.py
Labels: blended, needs triage

#1480 [BD-5] [TNL-7282] [BB-2621] Support flexible peer grading
  openassessment/assessment/api/peer.py
  openassessment/assessment/test/test_peer.py
  openassessment/locale/en/LC_MESSAGES/django.po
  openassessment/locale/en/LC_MESSAGES/djangojs.po
  openassessment/locale/eo/LC_MESSAGES/django.mo
  openassessment/locale/eo/LC_MESSAGES/django.po
  openassessment/locale/eo/LC_MESSAGES/djangojs.po
  openassessment/templates/openassessmentblock/edit/oa_edit_peer_assessment.html
  openassessment/workflow/api.py
  openassessment/xblock/defaults.py
  openassessment/xblock/schema.py
  openassessment/xblock/static/js/openassessment-studio.js
  openassessment/xblock/static/js/openassessment-studio.min.js
  openassessment/xblock/static/js/spec/studio/oa_edit.js
  openassessment/xblock/static/js/spec/studio/oa_edit_assessments.js
  openassessment/xblock/static/js/src/studio/oa_edit_assessment.js
  openassessment/xblock/test/test_openassessment.py
  openassessment/xblock/test/test_self.py
  openassessment/xblock/workflow_mixin.py
  openassessment/xblock/xml.py
  package-lock.json
  package.json
  setup.py
Labels: blended, needs triage

#1549 [BB-3269] [BTR-48] Fix writing binary files like images/pdf
  openassessment/fileupload/backends/filesystem.py
  openassessment/fileupload/tests/test_api.py
  openassessment/fileupload/views_filesystem.py
Labels: open-source-contribution, waiting on author

#1540 Made the badge point to travis-ci.com
  README.rst
Labels: community manager review, open-source-contribution
